// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: langgraph/v1/agent.proto

package langgraphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserInput     string                 `protobuf:"bytes,2,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // "chat" | "rag"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_langgraph_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_langgraph_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_langgraph_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *AgentRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

// Tool call emitted by the LLM node
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgsJson      string                 `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"` // serialized tool arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_langgraph_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_langgraph_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_langgraph_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

// Result from tool execution
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // tool output
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_langgraph_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_langgraph_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_langgraph_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ToolResult) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Streaming event from the agent graph
type AgentEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "tool_call" | "tool_result" | "text" | "error" | "message"
	// Types that are valid to be assigned to Content:
	//
	//	*AgentEvent_Text
	//	*AgentEvent_Error
	//	*AgentEvent_ToolCall
	//	*AgentEvent_ToolResult
	//	*AgentEvent_Message
	Content       isAgentEvent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_langgraph_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_langgraph_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_langgraph_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AgentEvent) GetContent() isAgentEvent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentEvent) GetText() string {
	if x != nil {
		if x, ok := x.Content.(*AgentEvent_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *AgentEvent) GetError() string {
	if x != nil {
		if x, ok := x.Content.(*AgentEvent_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *AgentEvent) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Content.(*AgentEvent_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *AgentEvent) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Content.(*AgentEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *AgentEvent) GetMessage() string {
	if x != nil {
		if x, ok := x.Content.(*AgentEvent_Message); ok {
			return x.Message
		}
	}
	return ""
}

type isAgentEvent_Content interface {
	isAgentEvent_Content()
}

type AgentEvent_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"` // text chunk or final response
}

type AgentEvent_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // error message
}

type AgentEvent_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3,oneof"` // LLM emitted a tool call
}

type AgentEvent_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3,oneof"` // tool execution result
}

type AgentEvent_Message struct {
	Message string `protobuf:"bytes,6,opt,name=message,proto3,oneof"` // intermediate message
}

func (*AgentEvent_Text) isAgentEvent_Content() {}

func (*AgentEvent_Error) isAgentEvent_Content() {}

func (*AgentEvent_ToolCall) isAgentEvent_Content() {}

func (*AgentEvent_ToolResult) isAgentEvent_Content() {}

func (*AgentEvent_Message) isAgentEvent_Content() {}

// Unary response (single text response, no streaming)
type AgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*AgentResponse_Text
	//	*AgentResponse_Error
	Result        isAgentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_langgraph_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_langgraph_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_langgraph_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentResponse) GetResult() isAgentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AgentResponse) GetText() string {
	if x != nil {
		if x, ok := x.Result.(*AgentResponse_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *AgentResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*AgentResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isAgentResponse_Result interface {
	isAgentResponse_Result()
}

type AgentResponse_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type AgentResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AgentResponse_Text) isAgentResponse_Result() {}

func (*AgentResponse_Error) isAgentResponse_Result() {}

var File_langgraph_v1_agent_proto protoreflect.FileDescriptor

const file_langgraph_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18langgraph/v1/agent.proto\x12\flanggraph.v1\"k\n" +
	"\fAgentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"user_input\x18\x02 \x01(\tR\tuserInput\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\"K\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\tR\bargsJson\"H\n" +
	"\n" +
	"ToolResult\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xf4\x01\n" +
	"\n" +
	"AgentEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x125\n" +
	"\ttool_call\x18\x04 \x01(\v2\x16.langgraph.v1.ToolCallH\x00R\btoolCall\x12;\n" +
	"\vtool_result\x18\x05 \x01(\v2\x18.langgraph.v1.ToolResultH\x00R\n" +
	"toolResult\x12\x1a\n" +
	"\amessage\x18\x06 \x01(\tH\x00R\amessageB\t\n" +
	"\acontent\"G\n" +
	"\rAgentResponse\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result2\x9a\x01\n" +
	"\fAgentService\x12C\n" +
	"\bRunAgent\x12\x1a.langgraph.v1.AgentRequest\x1a\x1b.langgraph.v1.AgentResponse\x12E\n" +
	"\vStreamAgent\x12\x1a.langgraph.v1.AgentRequest\x1a\x18.langgraph.v1.AgentEvent0\x01B5Z3github.com/mike00028/golang-backend/pkg/langgraphv1b\x06proto3"

var (
	file_langgraph_v1_agent_proto_rawDescOnce sync.Once
	file_langgraph_v1_agent_proto_rawDescData []byte
)

func file_langgraph_v1_agent_proto_rawDescGZIP() []byte {
	file_langgraph_v1_agent_proto_rawDescOnce.Do(func() {
		file_langgraph_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_langgraph_v1_agent_proto_rawDesc), len(file_langgraph_v1_agent_proto_rawDesc)))
	})
	return file_langgraph_v1_agent_proto_rawDescData
}

var file_langgraph_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_langgraph_v1_agent_proto_goTypes = []any{
	(*AgentRequest)(nil),  // 0: langgraph.v1.AgentRequest
	(*ToolCall)(nil),      // 1: langgraph.v1.ToolCall
	(*ToolResult)(nil),    // 2: langgraph.v1.ToolResult
	(*AgentEvent)(nil),    // 3: langgraph.v1.AgentEvent
	(*AgentResponse)(nil), // 4: langgraph.v1.AgentResponse
}
var file_langgraph_v1_agent_proto_depIdxs = []int32{
	1, // 0: langgraph.v1.AgentEvent.tool_call:type_name -> langgraph.v1.ToolCall
	2, // 1: langgraph.v1.AgentEvent.tool_result:type_name -> langgraph.v1.ToolResult
	0, // 2: langgraph.v1.AgentService.RunAgent:input_type -> langgraph.v1.AgentRequest
	0, // 3: langgraph.v1.AgentService.StreamAgent:input_type -> langgraph.v1.AgentRequest
	4, // 4: langgraph.v1.AgentService.RunAgent:output_type -> langgraph.v1.AgentResponse
	3, // 5: langgraph.v1.AgentService.StreamAgent:output_type -> langgraph.v1.AgentEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_langgraph_v1_agent_proto_init() }
func file_langgraph_v1_agent_proto_init() {
	if File_langgraph_v1_agent_proto != nil {
		return
	}
	file_langgraph_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentEvent_Text)(nil),
		(*AgentEvent_Error)(nil),
		(*AgentEvent_ToolCall)(nil),
		(*AgentEvent_ToolResult)(nil),
		(*AgentEvent_Message)(nil),
	}
	file_langgraph_v1_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentResponse_Text)(nil),
		(*AgentResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_langgraph_v1_agent_proto_rawDesc), len(file_langgraph_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_langgraph_v1_agent_proto_goTypes,
		DependencyIndexes: file_langgraph_v1_agent_proto_depIdxs,
		MessageInfos:      file_langgraph_v1_agent_proto_msgTypes,
	}.Build()
	File_langgraph_v1_agent_proto = out.File
	file_langgraph_v1_agent_proto_goTypes = nil
	file_langgraph_v1_agent_proto_depIdxs = nil
}
